### ISSUE TITLE
This can be built to provide api for client calls?

### ISSUE THREAD

**Issue by zengcanxiang** [psi-4ward/psitransfer#1]
I think we can provide a built-in api module for use, so that even if the individual user to deploy the use, can be used in the mobile side.thanks you open sources.

**Comment by psi-4ward** [comment]
Hey, I'm sorry but I don't fully understand your request :)

**Comment by zengcanxiang** [comment]
oh,sorry.
I mean the development of api, you can let non-website can also get data.,to Android and iOS provided. Restful api

**Comment by psi-4ward** [comment]
You have a clear separation between the up-/dowload apps with a REST-like interface but you have to support the TUS protocol for uploads.
See [lib/endpoints.js](https://github.com/psi-4ward/psitransfer/blob/master/lib/endpoints.js)
