### ISSUE TITLE
Can't change retention time on EDGE

### ISSUE THREAD

**Issue by kojo1984** [psi-4ward/psitransfer#10]
Whe you choose a file to upload, you change retention time from default to value you want, press "Upload", file gets uploaded and retention time is restored to default value "1 week".

**Comment by kojo1984** [comment]
Was using Docker container with tags psitrax/psitransfer:latest, psitrax/psitransfer:1 and psitrax/psitransfer:1.1.

**Comment by psi-4ward** [comment]
Can't reproduce.
