### ISSUE TITLE
Uploading Folders

### ISSUE THREAD

**Issue by RHuehne** [psi-4ward/psitransfer#102]
PSITransfer is really cool!

I just fell over one little thing:
I was wondering, why uploading multiple files is working fine, but drag & drop a Folder with files won't work, but create a single Dummy-File on PsiTransfer. Was this made to make sure, there is no recursive uploading of subfolders?

Thanks!

**Comment by psi-4ward** [comment]
The App is file-based and doesnt know about a folder structure. Dropping a folder is somewhat OS and Browser specific. On my Linux machine with Chromium it adds all files from the dropped folder flatted.
