### ISSUE TITLE
[Feature request] Unlimited retention

### ISSUE THREAD

**Issue by KaKi87** [psi-4ward/psitransfer#108]
Hello,

I need to allow unlimited retention on my own instance.

How do I do that ?

Thanks

**Comment by mr-propre** [comment]
At the root of the project, you can find a file named `config.js`. Open it with an IDE/text editor and in the `const config` variable, add a key/value pair to the `retention` object with a single character like `i` as key and a label for this retention option. This should looks like:

```
const config = {
    [...],
    "retention": {
        [...],
        "i": "Unlimited"
    }
}
```

As far as I experimented, the retention seems infinite when using this option.

**Comment by KaKi87** [comment]
I'll try, thanks !

**Comment by psi-4ward** [comment]
**`"i": "Unlimited"`: That's just wrong. Do not use "Unlimited"!**

There is no "unlimited" and PsiTransfer is not intended to be a permanent storage.
But you can use a VERY LONG expire time like `3600*24*365*10` for about 10 years.

**Comment by KaKi87** [comment]
@psi-4ward in that case, why didn't the program throw an error when @mr-propre tried it ?

And if there's really no data validation on the configuration file but only an lesser/greater check, would the `Infinity` value work ?

Otherwise, my feature request still stands, because I don't intend for my files to ever be deleted so I do really need permanent retention, or,  at least, a century.

Would a century's duration in seconds be greater than JS's max safe integer ? 😅

**Comment by psi-4ward** [comment]
The config.js validation is really not bullet-proof.
Retentions are object-keys and so they are Strings which are casted to Number. 

Event for Milliseconds 100 years are not a problem:
```javascript
3600*24*365*100 * 1000 < Number.MAX_SAFE_INTEGER // true
```

**Comment by KaKi87** [comment]
How about the rest of the program, is it bulletproof ?

**Comment by martin-braun** [comment]
@psi-4ward Just a little question. Will files automatically purged from the server when retention is over?

**Comment by psi-4ward** [comment]
> @psi-4ward Just a little question. Will files automatically purged from the server when retention is over?

yes: https://github.com/psi-4ward/psitransfer/blob/master/lib/db.js#L17 which invokes https://github.com/psi-4ward/psitransfer/blob/master/lib/db.js#L113

**Comment by martin-braun** [comment]
@psi-4ward I guess this code runs on every page load or is there a worker in the background?

The reason I ask is, an instance that is not visited could keep hotlinks active despite a past retention. I.e. I download a protected file and remember the hotlink. Then the website won't be visited for weeks. Despite a retention of 1 week, I can still download the file via hotlink afterwards.

Right now, my cron-job downloads a tiny file to check availability. If retention is checked on page load, I will change it to poll the entry page, instead.

**Comment by psi-4ward** [comment]
We are not using PHP here so it does not depend on any page-load. The cleanup function gets executed at the specified interval.

Just try it out: Run a local PsiTransfer instance, upload stuff and wait while watching your data-directory.
