### ISSUE TITLE
Download bucket not found

### ISSUE THREAD

**Issue by red-erik** [psi-4ward/psitransfer#111]
Hello,
thank you for your great software.
On the Admin page, I don't have the list of files but only "Download bucket not found".
I'm I missing something ?

Regards,

Red.

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/master/config.js#L37

**Comment by red-erik** [comment]
Thank you, sorry for the question but I'm not an expert and had a lot of difficulties to have it running on Win 2016.
I did not see that anyway, it is working great.

Regards,

Red.
