### ISSUE TITLE
config.production.js parameters not applied

### ISSUE THREAD

**Issue by red-erik** [psi-4ward/psitransfer#115]
Hello,
I'm not a Linux exert and I tried to follow, step by step, your instructions.
If I modify config.js everything is immediately applied but if I modify config.production.js
nothing happens.
What am I missing ?
Thank you in advance for your help.
Regards,
Red.

**Comment by greecemunky** [comment]
This may happen if you didn’t run the install command prefixed with NODE_ENV variable.  See the “Manual, precompiled” section.

How did you install/deploy it?

**Comment by psi-4ward** [comment]
the `production` in `config.production.js` matches the `NODE_ENV` environment variable. Be sure to have it set before you start the app or just edit `config.js`, its also valid.

**Comment by red-erik** [comment]
Hello,
I followed you "Manula Precompiled Instructions" with:

# Be sure to have NodeJS >= 12
$ node -v
v12.4.0

# Download and extract latest release package from
# https://github.com/psi-4ward/psitransfer/releases

# Install dependencies and start the app
$ NODE_ENV=production npm install
$ npm start

Regards,
Red.

**Comment by red-erik** [comment]
Hello,
my fault (as usual). I use PM2 to manage apps and FORGOT to use "--env production" when starting application.
Thank you for your work.
Regards,
Red.
