### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by edimusrex** [psi-4ward/psitransfer#12]
All of my web traffic gets forwarded to ssl, I can't seem to find away to allow psitransfer to listen on HTTPS

**Comment by kojo1984** [comment]
Create a reverse proxy in front of it using NginX, for example.
I don't think SSL is supported by it self...

**Comment by kojo1984** [comment]
https://github.com/psi-4ward/psitransfer/tree/master/docs

File called "nginx-ssl-example.conf"

**Comment by psi-4ward** [comment]
If it's requested by many users I can implement native SSL support

**Comment by edimusrex** [comment]
SSL support would be great.  I am using apache but I will take a look at the nginx-ssl file.

Thank you

**Comment by psi-4ward** [comment]
See f7ceb57 and try the latest master build.
