### ISSUE TITLE
BUG - Ignore incoming URL addons such as fbclid

### ISSUE THREAD

**Issue by tubalainen** [psi-4ward/psitransfer#121]
When sharing a download link with people via social medias the social media platform normally adds a `clid `to the URL when the downloader clicks on the shared link. The causes PsiTransfer to say "404 Not Found".

Example of a broken shared URL via Facebook Messenger: http://my.superserver.edu:3000/618cf2c17d5c?fbclid=IwAR2AqhUPNlgWghXVvXyTNRaesLzvz8QM78EqvczhfolPMFnwCj_gahasz08

Facebook (in this example) adds: `?fbclid=IwAR2AqhUPNlgWghXVvXyTNRaesLzvz8QM78EqvczhfolPMFnwCj_gahasz08` to the URL.

![image](https://user-images.githubusercontent.com/26795429/99240116-523e7980-27fc-11eb-9c24-5d57d64159ee.png)

**Comment by modem7** [comment]
Yup, just got this bug myself
