### ISSUE TITLE
Single file: Copy link to clipboard is broken

### ISSUE THREAD

**Issue by mr-propre** [psi-4ward/psitransfer#122]
Hello,

When copying the direct link of a single file in a bucket (clicking the copy button next to the preview button), the copied link is incorrect. Example:

https://myserver.com//files/514deba7c783++0161a5ed-3650-4f53-b112-7d931a536daa

is copied instead of:

 https://myserver.com/files/514deba7c783++0161a5ed-3650-4f53-b112-7d931a536daa

Seems like it adds an extra / after the domain name.

**Comment by mr-propre** [comment]
The fix for this is simple, just use substring:

In Download.vue modify the line 93 to:

`baseURI: this.$root.baseURI.substring(0, this.$root.baseURI.length - 1) ` 
and it'll work :)

I'll PR this fix along with some new features once I'm done developing them.

**Comment by psi-4ward** [comment]
Thats correct. @mr-propre please prepare small PRs for every feature - not a big one.
