### ISSUE TITLE
Feature Request: Add upload file size limit

### ISSUE THREAD

**Issue by atila01380** [psi-4ward/psitransfer#128]
It will be great to have an upload file size limit in  config files or admin panel !!!!

Thanks for your great job

**Comment by hb-i** [comment]
For Nginx you can use `client_max_body_size`. For Apache I think it's `LimitRequestBody`.

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/master/config.js#L59

**Comment by it-doggo** [comment]
> https://github.com/psi-4ward/psitransfer/blob/master/config.js#L59

Somehow this confuses me. Does a gigabyte number have to go in there now or what exactly?
