### ISSUE TITLE
download .zip or tar.gz is broken

### ISSUE THREAD

**Issue by merentitis** [psi-4ward/psitransfer#129]
It seems that while clicking at one of these two options, the request goes to: `http://myserverfiles//SOMESTRING` instead of `http://myserver/files/SOMESTRING`. 
I fixed it manually by editing "download.js":
```
- $root.baseURI+"files/"+this.sid+"++"+d()
+ $root.baseURI+"/files"+this.sid+"++"+d()
```

**Comment by kvnnap** [comment]
Have the same issue

**Comment by psi-4ward** [comment]
do you use the latest master version?
have you setup a correct base-url: https://github.com/psi-4ward/psitransfer/blob/master/config.js#L11

**Comment by kvnnap** [comment]
@psi-4ward I am using the latest docker image: psitrax/psitransfer from https://hub.docker.com/r/psitrax/psitransfer

Not sure how I would make edits to config.js without building the docker image again. Is it configurable for docker?

**Comment by merentitis** [comment]
> do you use the latest master version?
> have you setup a correct base-url: https://github.com/psi-4ward/psitransfer/blob/master/config.js#L11

I am too using the latest docker image

**Comment by kvnnap** [comment]
Ok, from reading config.js I think we can pass base url from docker using: `-e PSITRANSFER_BASE_URL=/`

However, I do not think I need to set this. I am running psitransfer at the root. ex: http://mydomain.com:3000/.

I just used the simple docker run command supplied in the instructions. It uploads correctly, it downloads a single file correctly but zip/tar.gz wont work. It generates a js error:

![image](https://user-images.githubusercontent.com/16206628/101172995-32071b00-3642-11eb-848a-61f74e79df2c.png)

Note the two forward-slashes after the ...3000files. When i fix the url manually to ...3000/files/... it then works.

**Comment by psi-4ward** [comment]
Pls let me know if it works for you.

**Comment by kvnnap** [comment]
@psi-4ward yes it works now 👍  Thanks!

**Comment by psi-4ward** [comment]
can u also run a test with custom `baseUrl` and `uploadAppPath` ?

**Comment by merentitis** [comment]
Downloading .zip or tar.gz works fine in latest docker image, was already using custom uploadAppPath, also tested with a  "baseUrl": '/test'.
Thank you!

**Comment by kvnnap** [comment]
Not sure if `baseUrl` is fully functional. When testing with `baseUrl:/test/`, I get redirected to `/`.

So, if i visit http://domain:3000/test/ it goes to http://domain:3000/ - Wrong?
If I visit http://domain:3000/test/admin, I stay on that location. - Correct

This has the negative effect of going to the wrong location which is an issue if I'm using a reverse proxy (nginx for instance), as I potentially go to the home page.

Not sure what is the use case for `uploadAppPath`, so not really sure how to test it.

**Comment by psi-4ward** [comment]
uploadAppPath is the url for the upload app so you should set it to baseUrl in your case to avoid the redirect. 

But I think many user would run into that issue so I will implement a fix for that case.

Thx for the hint!

**Comment by merentitis** [comment]
> 
> 
> Not sure if `baseUrl` is fully functional. When testing with `baseUrl:/test/`, I get redirected to `/`.
> 
Same for me, nothing seems broken though. I am also using a reverse proxy so I guess it is no use for me, but let the dev explain for sure.
> 
> Not sure what is the use case for `uploadAppPath`, so not really sure how to test it.
I am using it to restrict outside access to my admin and upload paths:
```
<Locationmatch "/upload|admin">
                Order Deny,Allow
                Deny from all
                Allow from x.x.x.x
</Locationmatch>
```

**Comment by psi-4ward** [comment]
I've improved this.

`uploadAppPath` let's you set a defined URL for the Upload-Interface

* `baseUrl=/psitransfer` and  `uploadAppPath=/` (default / not-set):
  * Upload using `/psitransfer`
  * Download using `/psitransfer/....`

* `baseUrl=/psitransfer` and `uploadAppPath=/upload`
  * Upload using `/upload`
  * Download using `/psitransfer/....`

The idea was to have a dedicated URL for all uploads to be able to add some logic in a proxy (like auth) to the upload process.

Of course you could use  `baseUrl=/psitransfer` and `uploadAppPath=/psitransfer/upload` to have the upload nested under baseUrl

**Comment by psi-4ward** [comment]
PS: If you understand and verify these cases we should release a new version.
It would please me if anyone could prepare a PR to document this settings in a better way.
