### ISSUE TITLE
Proxy with NGINX issue

### ISSUE THREAD

**Issue by edimusrex** [psi-4ward/psitransfer#13]
I've managed to get PsiTransfer running through a proxy using nginx and the ssl conf as shown in your documentation, however, I now get and error 

>  Download bucket not found. 

I've tried changing the uploadDir parameter but it doesn't seem to help.  Thank you

**Comment by psi-4ward** [comment]
Does it work if you access PsiTransfer without the proxy?

**Comment by edimusrex** [comment]
I think the issue is with my nginx redirects honestly, I ran multiple things on my web server so psitransfer is not at the root, it's in a sub url so I think that's what the issue is.  I will look into the ssl support though that you committed and try that.  Thanks

**Comment by psi-4ward** [comment]
It's not supported to deploy PsiTransfer as subfolder (yet).

**Comment by edimusrex** [comment]
ok, than that is definitely the issue.  I will try to run a web server on another server and proxy to that.  Thank you

**Comment by psi-4ward** [comment]
You don't need another webserver but a (sub)domain

**Comment by edimusrex** [comment]
good point, thanks
