### ISSUE TITLE
Admin console

### ISSUE THREAD

**Issue by edimusrex** [psi-4ward/psitransfer#14]
Would be very beneficial to have an admin page in which you could see all shares, share links, days remaining on retention etc.  Just a nice enhancement request.

Love this product by the way.

**Comment by psi-4ward** [comment]
Hmm this is not a trivial request, let's see if this request receives some up-votes.

**Comment by edimusrex** [comment]
thank you

**Comment by OrbGid** [comment]
+1

**Comment by psi-4ward** [comment]
Pls test latest master:

* set `adminPass` property in your config
* browse to `/admin`

**Comment by AnarchyInc** [comment]
Forgive me for what may be a obvious question.  Where do i actually set the adminPass password? I get that setting the value to True allows admin page but how do i change that password?
