### ISSUE TITLE
ARM Image

### ISSUE THREAD

**Issue by antoine2tt** [psi-4ward/psitransfer#143]
Hello,

Are they any ARM Image for Psitransfer ? 

i really like this soft, but i'm running on a Mac Mini with Apple M1 (so.. it's arm based)

And i didn't find any arm images here : https://hub.docker.com/r/psitrax/psitransfer/tags?page=1&ordering=last_updated

:(

**Comment by psi-4ward** [comment]
I don't know how to auto-build arm images using docker hub. But you can create the image yourself on your arm machine
