### ISSUE TITLE
Error download .zip or tar.gz

### ISSUE THREAD

**Issue by anthonypacitto** [psi-4ward/psitransfer#145]
Hi i'm using the latest docker version of psitransfert and I can't get zip nor tar DL working with a subdomain. 
If anyone has a solution i would be interested.

**Comment by psi-4ward** [comment]
Pls provide more information

**Comment by Aerya** [comment]
Hi,

Same here. I host Psi on https://files.domain.com and I can't use grouped DL to get files. Same URL for upload/download.

**Comment by o3web** [comment]
Hi,

Try to remove "/" after "files" in downloadAll() function (line 130 for me)

` downloadAll(format) {
        document.location.href = this.$root.baseURI
          + '/files' + this.sid + '++'
          + MD5(
            this.files
              .filter(f => !f.downloaded || f.metadata.retention !== 'one-time')
              .map(f => f.key).join()
          ).toString() + '.' + format;

        this.files.forEach(f => {
          f.downloaded = true;
        });
      },

      copied(file, $event) {
        file.downloaded = $event === 'copied';
      },`

**Comment by Aerya** [comment]
Thanks but I don't want to edit the Docker. I'll wait for a PR to correct this.

**Comment by psi-4ward** [comment]
> Try to remove "/" after "files" in downloadAll() function (line 130 for me) in Download.vue
> 
> `document.location.href = this.$root.baseURI + '/files' + this.sid + '++' + MD5( this.files .filter(f => !f.downloaded || f.metadata.retention !== 'one-time') .map(f => f.key).join() ).toString() + '.' + format;`

It's  not that simple cause one can run PsiTransfer in subdirs now.
