### ISSUE TITLE
SOLVED: Request Entity Too Large

### ISSUE THREAD

**Issue by geocheats2** [psi-4ward/psitransfer#149]
I am trying to upload a zip file with size of 13.4mb and i get this error

I am running psitransfer in a docker container with stock settings apart from the port which is bound to 3001

`
tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /files/25bc6612ce40++0d4e0058-1cf9-45e5-a0c6-880069cc8aaa, response code: 413, response text: <html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.14.2</center> </body> </html> , request id: n/a)`

Do you have any recommendations 
Thanks in advance
George

**EDIT

Sorry for the attention

Solved 

Had to set 

client_max_body_size 100M;

on nginx**

**Comment by psi-4ward** [comment]
Should be not a problem cause of https://github.com/psi-4ward/psitransfer/blob/master/app/src/Upload/store/upload.js#L155
