### ISSUE TITLE
Feature: Download confirmation(report)

### ISSUE THREAD

**Issue by kojo1984** [psi-4ward/psitransfer#16]
Is there a way to to confirm that remote user has downloaded a file?

Or, to have some kind of logging feature available?

Tnx

**Comment by psi-4ward** [comment]
Currently you can only take a look at the access logs.

**Comment by OrbGid** [comment]
Where is the access log located ?

**Comment by psi-4ward** [comment]
depends on how you run psitransfer
`docker logs psitransfer | grep -F 'GET '/files/`
