### ISSUE TITLE
[Question] How to edit the page?

### ISSUE THREAD

**Issue by Joshii01** [psi-4ward/psitransfer#164]
Hello there @psi-4ward ! i have looked around the files for a bit but i cant seem to figure out which file is the one that controls the web page. can you please help me out? thanks! <3

**Comment by Joshii01** [comment]
Nevermind, i figured it out! <3

**Comment by psi-4ward** [comment]
No comment how to solve this for others?

**Comment by Joshii01** [comment]
@psi-4ward sorry! you just need to edit the .pug files and wait for the page to update.

**Comment by Joshii01** [comment]
then it should change
