### ISSUE TITLE
Option to hide New Upload button

### ISSUE THREAD

**Issue by greecemunky** [psi-4ward/psitransfer#17]
Can a config option be provided to hide the New Upload button?  I ask this as I plan on using PsiTransfer to send files to clients, however I want it to be one-way only (we upload files to share with clients, clients should not upload files to share with us or anyone else).

Our test instance of PsiTransfer is served via an Apache SSL reverse proxy.  To prevent clients from uploading files we have only allowed our IP addresses to access location /.  Staff will know they need to access / to upload a file, so they should not _need_ the button.  The resulting HTTP 403 error users outside of the whitelisted IP addresses receive when accessing / will redirect to our homepage, but I would like the button removed to hinder any inclination they may have of pushing it.

Alternatively, when said option is set to hide the New Upload button, it should appear only when accessing / or an error page resulting from a failed upload.

**Comment by psi-4ward** [comment]
What about a little CSS?
```
.btn-new-session { display:none }
```

**Comment by greecemunky** [comment]
@psi-4ward Thanks!  I added `display:none;` to `.btn-new-session` within `public/assets/styles.css` (didn't need to remove the other stuff) and it works perfectly.
