### ISSUE TITLE
Upload history, what - when

### ISSUE THREAD

**Issue by torisevt** [psi-4ward/psitransfer#173]
We are using PsiTransfer as our business file transfer hub.
One of our users made a statement that, is there possible to keep track what filenames where uploaded and when.
Just filenames, not actual files.

**Comment by psi-4ward** [comment]
Theres the [fileUploadedWebhook](https://github.com/psi-4ward/psitransfer/blob/master/plugins/file-uploaded-webhook.js) 
use it to trigger some _tracking_ system
