### ISSUE TITLE
Reverse Proxy Compatibility

### ISSUE THREAD

**Issue by titeishon** [psi-4ward/psitransfer#18]
Hi

I'm using running PsiTransfer on a docker container and I have set up nginx as reverse proxy. 
I can access the site but when I try to upload a file I get this error:

` tus: unexpected response while uploading chunk, originated from request (response code: 413, response text: <html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.13.0</center> </body> </html> )`

if I do the same operation with the IP:Port url it works wonders. Is there something I can do make it work with the reverse proxy?

thanks for your help!

**Comment by titeishon** [comment]
I also noticed that the 3000 port can't be easily changed. I tried forwarding the port through docker with the [Containter:Host] port scheme, but it won't resolve if it isn't 3000.

**Comment by psi-4ward** [comment]
It's not a Port problem cause you receive a `413 Request Entity Too Large`.
Your nginx needs a bigger `client_max_body_size`.

Greets
