### ISSUE TITLE
Cancel button not working

### ISSUE THREAD

**Issue by OrbGid** [psi-4ward/psitransfer#19]
Hello,
First of all, thank you for taking your time to build this nice and smooth (web)app :) !

I just found an issue, after upload starts, there is no way to cancel it. Cancel button doesn't work.

Regards,
Andrei

**Comment by psi-4ward** [comment]
Which button do you mean? Can you paste a screenshot? Did you take a look into your dev console?

**Comment by psi-4ward** [comment]
Closed due inactivity.
