### ISSUE TITLE
Upload Pass

### ISSUE THREAD

**Issue by chrissthedrummer** [psi-4ward/psitransfer#195]
Can anyone help me understand how UloadPass works- which function checking if password is valid?

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/c438d5b839d3bf2277e246b462e740e016ea62ba/lib/endpoints.js#L298
It's in the x-passwd header

**Comment by chrissthedrummer** [comment]
Great. Thanks for Your help. One last question- where in code "x-passwd" is set in request header on login button click?
