### ISSUE TITLE
Feature: Option to send links via email

### ISSUE THREAD

**Issue by citydweller1985** [psi-4ward/psitransfer#2]
Hi,

an option to send links from uploaded files via email would be great.
And also an info to the uploader, if the file is first downloaded from the receiver.

Regards
Danny

**Comment by psi-4ward** [comment]
Hi Danny,

sharing the exact dowload-links is not wanted cause it will bypass the password-check and blocks future improvements like payload encryption. Sharing a _Bucket_ is part of the concept.

Informing the uploader by mail? I want to keep this App simple and without mail-sending stuff.
But we could display a "last downloaded" timestamp in the downloads-list.
