### ISSUE TITLE
Some android phone can not upload

### ISSUE THREAD

**Issue by gexqin** [psi-4ward/psitransfer#20]
I have 3 android device. 2 of them working fine but my HUAWEI P9(android 7) doesn`t work.  Only upload not work download works. You can select files,photo,video and click upload button then nothing happen.
It may be due to android 7 or HUAWEI P9`s security setting I don`t know. Is any logs I can check at server?

**Comment by psi-4ward** [comment]
It's a browser problem, you need to remote debug it.
I've tested it with some devices but it works for me

**Comment by gexqin** [comment]
I use different browser on that phone but same problem. I am sure this is my phones OS problem I just try to find out.

**Comment by psi-4ward** [comment]
Okay, I'll close this for now.
