### ISSUE TITLE
Pictures don't seem to load when using reverse proxy

### ISSUE THREAD

**Issue by EchoDev** [psi-4ward/psitransfer#21]
Hi,

I just got psitransfer "working". I installed NodeJS/NPM and I am using apache2 as a reverse proxy. For some reason the pictures on the site itself don't seem to load. Does anyone know how to fix this issue? No errors in NPM or Apache2 logs.

The only files that load are style.css, common.js, upload.js and config.json.
![5ef45d76e](https://user-images.githubusercontent.com/3149302/28184934-a78035fa-6815-11e7-8a79-f97aa532eb1d.png)

**Comment by psi-4ward** [comment]
Pls paste your apache config.
Seems also the bootstrap styling gets not loaded, it comes from the official CDN. 
Pls look into you dev console (press F12)

**Comment by EchoDev** [comment]
```
<VirtualHost 0.0.0.0:443>
                Include /etc/letsencrypt/options-ssl-apache.conf
                Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
                ProxyPreserveHost On
                ProxyPass / http://127.0.0.1:3000/
                ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```

I use HSTS, could that be causing issues?

**Comment by psi-4ward** [comment]
No, should be no Problem.
Any erros in dev console?

**Comment by EchoDev** [comment]
Error in parsing value for ‘width’.  Declaration dropped.

But I doubt a single css error would cause this heh

**Comment by psi-4ward** [comment]
definitely not

**Comment by EchoDev** [comment]
I just tested going straight to PsiTransfer and not using the reverse proxy and that gives no issues. Something seems wrong with the proxy.

**Comment by EchoDev** [comment]
Hmm...I think this is an issue on my end, the site works fine in Chrome when using the reverse proxy.

Situation for me is now:
Firefox - No Proxy: Working
Firefox - Proxy: Not Working
Chrome - No Proxy: Working
Chrome - Proxy: Working

You can close this issue if you want, I'm gonna try to find out why my Firefox setup is not working with the site. Thanks for the fast replies.

**Comment by psi-4ward** [comment]
Pls tell me the results, perhaps we can add a working config for apache to the docs.

**Comment by EchoDev** [comment]
It seems one of my request filter extension was set too strict and I had forgotten about it. Any reason for the css files to be hosted on BootstrapCDN?

For the working apache conf

```
<VirtualHost 0.0.0.0:80>
               ServerName psi.example.org
                ProxyPreserveHost On
                ProxyPass / http://127.0.0.1:3000/
                ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```

This is a barebones conf that will work. 2 mods need to be enabled for this
mod_proxy and mod_proxy_http.

**Comment by psi-4ward** [comment]
Cause it was easy. It would be way better to compile a stripped down version and include it.

**Comment by psi-4ward** [comment]
Did you try the config with really big files? Do we get buffer problems?

**Comment by EchoDev** [comment]
I haven't tried it yet, uploading a 1GB file atm. Should be done in ~30 minutes.

**Comment by psi-4ward** [comment]
Take a look at the mem consumption of the httpd process

**Comment by EchoDev** [comment]
httpd shows less than 1 MB
apache has ~12 processes running at 25MB each

**Comment by EchoDev** [comment]
I'm not noticing much from nodejs and apache when uploading a 1GB file. Uploads fine, cpu usage <5% (Intel Xeon E3-1225 @ 3.2Ghz), RAM usage <1%.

**Comment by psi-4ward** [comment]
Thats valid :+1:

**Comment by psi-4ward** [comment]
I think you could also drop `ProxyPreserveHost On`
PsiTransfer does not have any logic using the `Host` header

**Comment by EchoDev** [comment]
Yeah I grabbed that from an older config of mine. `ProxyPass / http://127.0.0.1:3000/` and `ProxyPassReverse / http://127.0.0.1:3000/` are the important bits for PsiTransfer and the rest of the conf is up to the user.
