### ISSUE TITLE
tar.gz Download consumes to much memory

### ISSUE THREAD

**Issue by louino2478** [psi-4ward/psitransfer#221]
can disable the button ".tar.xz" ?
because is make a out of memory crach when we used this button with big file

my psi transfert running in a docker container

**Comment by psi-4ward** [comment]
So zip and tar.gz archives should be generated using streams and it should _not_ consume much memory. If it does as you say there's possibly a bug in the backpressure handling of [archiver append](https://github.com/archiverjs/node-archiver/issues/414) and we need to change the implementation here.

To disable the button you can use a little CSS-Hack:
```
.btn-download-archive > .btn:nth-child(2) {
  display:none;
}}
```
