### ISSUE TITLE
Where is data stored ?

### ISSUE THREAD

**Issue by 7aklhz** [psi-4ward/psitransfer#223]
Hi, 

I cannot seem to find where the data is stored. I have defined the directory (/data) but when I enter my docker instance and look inside /data it is empty. I can however download the file(s) and I see them in the admin front page.

So, where is data stored please ?

**Comment by psi-4ward** [comment]
upload a bigger (ie 1G) and `find / -size +900M` in your container.... default is `/data` see https://github.com/psi-4ward/psitransfer/blob/master/Dockerfile#L3

**Comment by 7aklhz** [comment]
Thanks for avnswsering. I finally found it. I using docker and it's storing it under volumes /var/lib/docker/volumes/ and not inside the container. I'm starting out with docker so I wasn't familiar with that type of storing behavior
