### ISSUE TITLE
Apache reverse proxy example?

### ISSUE THREAD

**Issue by thestraycat** [psi-4ward/psitransfer#23]
Any chance we can get an example apache reverse proxy example... not working with:

 ##PSITransfer##
 <Location /transfer>
 ProxyPass http://192.168.1.125:3000/transfer
 ProxyPassReverse http://192.168.1.125:3000/transfer
 </Location>

formatting is all off :(

**Comment by psi-4ward** [comment]
Yes, currently there's no option to run transfer in a subdirectory.

See your dev console.
