### ISSUE TITLE
Browse and edit your files after upload

### ISSUE THREAD

**Issue by martin-braun** [psi-4ward/psitransfer#236]
Grüße gehen raus! 🙋🏼

Meta data of uploaded files could be stored within the localStorage, so that it could be used to manage uploaded files in this browser. It could also be coupled with user authentication #105.

**Comment by psi-4ward** [comment]
The PR #105 is outdated and there are forwarding proxies which can handle auth for you. PsiTransfer is to quickly share data, if you need more auth and edit features you should consider smth like NextCloud.

**Comment by martin-braun** [comment]
Yes, I could, but NextCloud / OwnCloud / etc. are too heavy for me. I use Syncthing which is great for file syncing, the only thing I miss is file sharing to external people. If this is not possible, I'm ok with that, I can look further. [projectsend](https://github.com/projectsend/projectsend) might be what I am looking for.
