### ISSUE TITLE
How to make http acces come https automaticly

### ISSUE THREAD

**Issue by gexqin** [psi-4ward/psitransfer#24]
PsiTransfer listening on http://0.0.0.0:80
PsiTransfer listening on https://0.0.0.0:443

How to make if I access http link then automaticly jump to https?

**Comment by psi-4ward** [comment]
Hi,
PsiTransfer usually runs behind a reverse proxy and does not support _force ssl_ but I'll implement this feature.

**Comment by EchoDev** [comment]
If you run PsiTransfer behind a reverse proxy I would recommend just to configure it in your proxy. In Apache2 is basically comes down to adding the following line in your virtualhost for port :80. I'm sure  nginx has the same option.

`Redirect / https://0.0.0.0`

@gexqin What setup do you use for PsiTransfer

**Comment by gexqin** [comment]
@EchoDev No I have no Apache2 or nginx installed on that vm. I just concern if  PsiTransfer could set 
 to force ssl.

**Comment by eitiewr** [comment]
@gexqin Well, for your internal network, I guess, you could perform some redirection in the app.js in the http-server to the https-server. That could look like this:
`// Save the current url`
`var link = 'https://' + req.headers.host + req.url;`
`// Delete the current port`
`var newLink = link.substring(0,link.lastIndexOf(':')+1);`
`Add the sslPort and redirect`
`res.redirect(newLink + config.sslPort);`

But that just works locally. For other purposes take the comment by @EchoDev 👍 

> If you run PsiTransfer behind a reverse proxy I would recommend just to configure it in your proxy. In Apache2 is basically comes down to adding the following line in your virtualhost for port :80. I'm sure nginx has the same option.

> Redirect

 / https://0.0.0.0
