### ISSUE TITLE
Bug: downloading zipfile on uploads with "one-time download" does not remove files/bucket

### ISSUE THREAD

**Issue by thutex** [psi-4ward/psitransfer#244]
Situation:
- upload multiple files
- set "one time download" retention
- get link
- go to download link
- download files using zip-button

Expected behaviour:
- receive zip file
- have bucket be removed

Actual behaviour:

You can keep downloading the files using the zip method.
All files will stay available as long as you only use the download zip method.

When you download a single file, that file does get correctly removed
If it is the last file in the bucket, the bucket will also be deleted.

**Comment by psi-4ward** [comment]
Cant reproduce
