### ISSUE TITLE
[Feature Request] Public downloads

### ISSUE THREAD

**Issue by foxtrot9** [psi-4ward/psitransfer#26]
I have idea of something called as public downloads.
What is it?
These are the uploads which are shown on server's front page (or any other page), all people can download it. (It can contains password based authentication so that only fee can download but links are open for everyone else to see.)

**Comment by psi-4ward** [comment]
This is tools is not designed as permanent file storage. If you need to, you can create a simple HTML page holding the bucket links with some description.
