### ISSUE TITLE
Auto-redirect the direct download link to its download page?

### ISSUE THREAD

**Issue by droplinxuser** [psi-4ward/psitransfer#265]
Basically the same as this request:
https://community.cloudflare.com/t/how-do-i-use-cf-rewrite-url-to-redirect-a-direct-link/475260

It would be great if it can be done on the main web app.

**Comment by Maytrok** [comment]
Hi,

i didn't get the point. A normal user does not know the direct file link, or i miss something.
However this can solved with csrf protection.
But i think the goal of this project is simplicity, so that will be not a thing

**Comment by droplinxuser** [comment]
Yeah, I've done this via nginx redirect and mapping now.
