### ISSUE TITLE
tus: invalid or missing offset value, originated from request

### ISSUE THREAD

**Issue by droplinxuser** [psi-4ward/psitransfer#272]
Full error:

```
tus: invalid or missing offset value, originated from request 
(method: HEAD, url: /files/00xxxxxxxxxx++xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, 
response code: 200, response text: , request id: n/a)
```

To re-produce:
- Open your PSI instance on the browser and open Browser Network Tools.
- Limit your internet speed to something like the preset "Slow 3G."
- Or create a custom one and limit the upload and download speeds to 1 MBps.
- Upload a big file, like 1 GB.
- Disconnect and re-connect on your internet during the upload several times, and that error will appear.

How do I fix this, please?
Related issue:
https://github.com/tus/tusd/issues/452

**Comment by droplinxuser** [comment]
I'm using Cloudflare, by the way, if that's relevant to the issue.

**Comment by psi-4ward** [comment]
Can u also produce this issue with a local installation of PsiTransfer?

**Comment by droplinxuser** [comment]
This is already fixed, thanks.

**Comment by Codename-404** [comment]
> This is already fixed, thanks.

Can you please share the solution? i am facing same issue with cloudflare

**Comment by droplinxuser** [comment]
Disable caching.

**Comment by Codename-404** [comment]
I am sorry, Where? I am using Next.js by the way.
Did you mean disable on worker or on next front end? 
It would be really helpful, if you can share a bit about where and how to do that.
