### ISSUE TITLE
generate a download link after upload

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [psi-4ward/psitransfer#274]
hello, j suppose that when i upload a file i got a new link as https://mysite/upload/abc123 and i want it has format as https://mysite/download/abc123, could you tell me how can i do that or that's need to be add to new version ? 
thank

**Comment by Maytrok** [comment]
Hey Anh,

you can easily archieve this with using a bucket id. The only part thats missing will be the "upload/download" path in the url

You have to call the site like this:

https://mysite?sid=abc123 

upload your files and there you go. your download link will be as you described

**Comment by AnhTuanNguyenn** [comment]
Thank @Maytrok, 
i was applied Write-On in htaccess :)
