### ISSUE TITLE
Upgrade nodejs

### ISSUE THREAD

**Issue by martin-braun** [psi-4ward/psitransfer#276]
node v14 is not maintained anymore, thus using it is a security risk.

![Releases](https://github.com/psi-4ward/psitransfer/assets/24259245/4062b9a4-0470-4f61-a52e-2a28c9890a6e)
[Source](https://nodejs.dev/en/about/releases/)

It would be great to get this raised to LTS (v20), which should be good until 2026 if I'm not mistaken.

**Comment by psi-4ward** [comment]
Current version runs on node 18: https://github.com/psi-4ward/psitransfer/blob/master/Dockerfile#L1

**Comment by psi-4ward** [comment]
2a95769fb6ad9e5160a30125a82908a765f6226e

**Comment by martin-braun** [comment]
@psi-4ward I was looking at https://github.com/psi-4ward/psitransfer/blob/master/.nvmrc, maybe we should update this to `20`.
