### ISSUE TITLE
Feature: Downloading all files from bucket

### ISSUE THREAD

**Issue by jiri-novacek** [psi-4ward/psitransfer#3]
If user uploads hundreds of files (photos or whatever) I am not able to download all files at once. 
Option to download everything as a zip file would be great.
User could zip them before uploading, but unfortunately for some users this is too complicated.
I can't even use browser addons like DownThemAll as it doesn't "see" the files.
Could any solution for this be found and implemented?
Thanks

**Comment by psi-4ward** [comment]
I've been thinking about this feature but it would break some others I've on my todo list like end-to-end encryption. 
But DownThemAll support should not a big deal if this would be sufficient for you?

**Comment by jiri-novacek** [comment]
To make links visible for DownThemAll would certainly be sufficient for me, but I would call that a workaround, not a solution. I think more users would be having same problem sooner or later.

Maybe make it as option if user/administrator is willing to sacrifice end-to-end encryption whatsoever? Or make it available only for passwordless buckets?

**Comment by psi-4ward** [comment]
That's correct.

I don't have a good solution for a cross-browser end-to-end decryption cause most don't implement Fetch, ServiceWorker and StreamAPI yet. 
So one solution for the decryption is to let the server do the work but we have to transfer the key over the wire and receive plaintext.

I'll rethink the download as ZIP feature.

**Comment by jiri-novacek** [comment]
I think anybody caring about security would be using https for accessing, so that helps with sending plaintext...?
Anyway, I feel like I can't be of much more help here, not knowing anything about Fetch,ServiceWorker or StreamAPI :)
Thank you for giving this feature more thinking, I'll be waiting and testing anything which might come in future versions.

**Comment by psi-4ward** [comment]
Checkout https://github.com/psi-4ward/psitransfer/tree/feature-download-zip 

You can help me to test the stuff, especially with `one-time` downloads.

**Comment by jiri-novacek** [comment]
Great! From my testing:
Clicking on ZIP/GZ button when all files from one-time download bucket have already been downloaded results in browser spinning (trying to load something what can't be generated?).

I don't know what compression level is used (probably default for some compression library?) but I think for this purpose (getting all files in one package) "store" level (no compression) should be used to save resources. Maybe best would be to have compression level configurable for server admin?

But aside from these cosmetic issues I don't see any problem, will test more.

**Comment by psi-4ward** [comment]
The issue should be fixed and I've merged the improvements from v1.0.0. Pls test again.

**Comment by psi-4ward** [comment]
Merged into master :)
