### ISSUE TITLE
stupid question but where can I find the admin password?

### ISSUE THREAD

**Issue by Hendrik292** [psi-4ward/psitransfer#303]

**Comment by lpirl** [comment]
Try ctrl + f "admin" on the [main page of this project](https://github.com/psi-4ward/psitransfer). :)

**Comment by Hendrik292** [comment]
And if I manually configure the server like this?

# Compile the frontend apps
$ cd app
$ npm install
$ npm run build

# Install dependencies
$ cd ..
$ npm install
$ npm start

> Try ctrl + f "admin" on the [main page of this project](https://github.com/psi-4ward/psitransfer). :)

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/master/config.js#L38

**Comment by Hendrik292** [comment]
> https://github.com/psi-4ward/psitransfer/blob/master/config.js#L38

But how can I change the password if I set the line to true?

**Comment by AlkoholLiga** [comment]
Configure this line like this to set the password:
`"adminPass": "YourSecurePassword",`

> https://github.com/psi-4ward/psitransfer/blob/master/config.js#L38

**Comment by Hendrik292** [comment]
![image](https://github.com/psi-4ward/psitransfer/assets/88030983/5eec2fd8-0294-4199-a75d-5d05b9f7b403)

But when I set a password there, my server no longer starts and this error message comes up

**Comment by psi-4ward** [comment]
you have to quote it like `'test'`

**Comment by Hendrik292** [comment]
ah okay thanks
