### ISSUE TITLE
Setting base_url via ENV

### ISSUE THREAD

**Issue by magnusoverli** [psi-4ward/psitransfer#308]
It would be very nice if we could set the base_url via environment variables.
I share files with others via cloudflare, but they limit the supported upload file size to 100MB via their tunnel. This means I connect locally to the instance and upload files, but the links generated are then also locally based.

**Comment by magnusoverli** [comment]
I see that the base_url is configurable via config.json, but as I am running psitranfser via docker compose I dont think config.json is exposed to me?

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/master/docs/configuration.md#environment-variables

https://github.com/psi-4ward/psitransfer/blob/master/docs/deployment-docker.md
