### ISSUE TITLE
Is it possible to allow special users to upload

### ISSUE THREAD

**Issue by DanielDavy** [psi-4ward/psitransfer#32]
If we host this on our own server, can we allow specified users or IP addresses to upload files to avoid abuse?

Thanks

**Comment by valentijnscholten** [comment]
I would be interested in this as well. If the upload and download url paths are completely seperate, this could be achieved by setting up authentication in apache/nginx.

**Comment by gertmenke** [comment]
+1
I'd prefer allowing special IP addresses over user accounts, to keep it simple.

**Comment by dottgonzo** [comment]
+1 (not only ip)

**Comment by psi-4ward** [comment]
Bundle the upload-app and upload-api inside `/up` is a good point. With this everyone could implement its own security gateway to handle auth (ie basic, ip-based, whatever)

**Comment by jdrews** [comment]
+1
