### ISSUE TITLE
Feature: Multilanguage support

### ISSUE THREAD

**Issue by jiri-novacek** [psi-4ward/psitransfer#4]
Hello, I have (another) suggestion :) 
Any chance of having multiple languages supported? It is just a couple of terms (retention, password, etc...) but might help some users.
UI language preferably configurable in config.*.js file either as constant or with "automatic" option (to use language according to what users browser header reports) with fallback to some default (EN) when browsers language is not available.

**Comment by psi-4ward** [comment]
It's on my list.

**Comment by janwerner** [comment]
I'd be glad to provide the German translation if you could provide the necessary infrastructure.

**Comment by Osrx** [comment]
I will help with Russian.
I'm also really need this!

**Comment by eternalharvest** [comment]
I will help with Japanese.
I'm also really need this too!

**Comment by jcmousse** [comment]
@janwerner, psi4ward

>  I did a quick & dirty manual translation for the time being
Jan, psi4ward, can you please tell me in which files i can translate the "drop you files here" or "new upload" captions ?

**Comment by jcmousse** [comment]
>  I did a quick & dirty manual translation for the time being
@janwerner psi4-4ward, can you tell me in which files i can translate "Drop your files here" or "new upload" captions ?

**Comment by jcmousse** [comment]
@janwerner @psi-4ward 
"I did a quick & dirty manual translation for the time being"
Can someone tell me in which files i can translate "Drop your files here" or "new upload" captions ?

**Comment by Osrx** [comment]
When When When?!

**Comment by psi-4ward** [comment]
In the next weeks. Hope we will find many translators :-)
