### ISSUE TITLE
Send password in SMS 

### ISSUE THREAD

**Issue by oded86w** [psi-4ward/psitransfer#43]
Hi ,  It's possible to add option to send the encrypt password in sms from the web ?
We have a SMS gateway that can recieve massage in GET protocol .
I want when user upload a file and set a password  he put the cellular number of the recipient and the racipient get the password in SMS .

**Comment by psi-4ward** [comment]
This use case is to specific to implement. sorry. 
But you can fork PsiTransfer and adjust it to your needs.
