### ISSUE TITLE
Setting PSITRANSFER_DEFAULTRETENTION="one-time" does not work

### ISSUE THREAD

**Issue by cazarottiv** [psi-4ward/psitransfer#44]
Hello!! 
First of all thanks for this great software!! 
One minor issue I noticed is that the default retention cannot be set to "one-time"
The application simply ignores it and the retention option starts blank.

Regards!!!

**Comment by lumbric** [comment]
I think you need to use `PSITRANSFER_DEFAULT_RETENTION`, an underscore is added when converting "defaultRetention" from camel case to upper case. See code in config.js for details.

**Comment by sandstormkeshav** [comment]
I am trying to use PSITRANSFER_DEFAULT_RETENTION environment variable to set the default retention but it does not seem to take. No matter what I set it to, it uses the default 604800 value.
