### ISSUE TITLE
js not loading properly through reverse proxy.

### ISSUE THREAD

**Issue by ndaringer** [psi-4ward/psitransfer#50]
I'm attempting to set up psitransfer through apache2 reverse proxy.
It loads as expected when connecting directly  http://dockerip:3000 https://i.imgur.com/X7hAjss.png
It has all kinds of issues when connecting through the proxy. https://i.imgur.com/cdUoHdH.png

Here is the console log from the browser.

```
 Failed to load resource: the server responded with a status of 404 (Not Found)
 common.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
 upload.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
 common.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
 upload.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
 styles.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

```
Happy to provide more information. Thanks.

**Comment by greecemunky** [comment]
What does your Apache reverse proxy configuration look like?  I’ll compare it to mine.

**Comment by ndaringer** [comment]
```
 <Location /psi>
 ProxyPass http://10.X.X.X:3000
 ProxyPassReverse http://10.X.X.X:3000
 ProxyPreserveHost On
 </Location>
```

This is my .conf in the sites-available folder. Not sure where else I should be looking for a conf file. This is all I've done to my reverse proxy server in regards to getting psitransfer to work through it.

**Comment by psi-4ward** [comment]
So you try to run PsiTransfer at a *subfolder* (/psi) but the html-pages request the assets on the root.
I'm very sorry but this is currently not supported. Pls add a subdomain for now.

You could try the PR from @xemle https://github.com/psi-4ward/psitransfer/pull/28 which should enable this but sadly I had no time to release a new major version.

**Comment by greecemunky** [comment]
Another option may be to utilize an Apache content-rewriting module to rewrite paths within the response body, in addition to your current reverse proxy setup.

https://httpd.apache.org/docs/2.4/mod/mod_substitute.html
https://httpd.apache.org/docs/2.4/mod/mod_sed.html

That said, I've not used either before nor do I don't know all paths that require handling.

Rough example:

```
<Location /psi>
ProxyPass http://10.X.X.X:3000
ProxyPassReverse http://10.X.X.X:3000
ProxyPreserveHost On
AddOutputFilterByType SUBSTITUTE text/html text/css application/javascript application/json
Substitute "s|/app|/psi/app|i"
Substitute "s|/assets|/psi/assets|i"
Substitute "s|/config.json|/psi/config.json|i"
Substitute "s|/files|/psi/files|i"
</Location>
```

When I get some free time I might test it myself.

**Comment by KaKi87** [comment]
Please @psi-4ward add support for ProxyPass in subfolder
