### ISSUE TITLE
No Upload Section

### ISSUE THREAD

**Issue by BirkHappens** [psi-4ward/psitransfer#51]
Hi,

I see the logo and the footer, but there is nothing else on the page for some reason.  I enabled DEBUG and I don't see any errors.  Seems a bit strange... any ideas?

Please and thanks so much!

**Comment by psi-4ward** [comment]
see the dev console of your browser

**Comment by BirkHappens** [comment]
Literally posted this and then saw the 404's for upload.js and common.js.  My fault.

Thank you!

**Comment by basu90** [comment]
Hi,
how did you solve the problem? I have the same. He is trying to load the common.js and upload.js. These are in /app/src but not in /app.

https://bit.ly/2FaaKGO
