### ISSUE TITLE
Fix font issue on Download page

### ISSUE THREAD

**Issue by hardida** [psi-4ward/psitransfer#52]
I have noticed that the font size is:

1. Quite large
2. Sometimes outside of the "Files" box (see image)
How can I correct this? I am very new to programming, so my experience is nil.
![download image](https://user-images.githubusercontent.com/39628716/40554000-679b8df4-6012-11e8-942e-474f41f50f34.PNG)

**Comment by psi-4ward** [comment]
what browser? did you increase the font-size? should not be such especially on small devices.
