### ISSUE TITLE
Security - Password is stored in clear text.

### ISSUE THREAD

**Issue by Super-Eric** [psi-4ward/psitransfer#56]
Description:
Security - Password is stored in clear text.

Steps:
1. Share one file
2. Check the data in folder, e.g.: ./data/1f2c4b2fdc85/031cc580-9a75-47b2-98ba-1c1ae89c0609.json

Expected:
The password for sharing in the file should be encrypted.

Actual:
The password for sharing is clear text here:
{
  "uploadLength": 115255,
  "metadata": {
    "sid": "1f2c4b2fdc85",
    "retention": "3600",
    "password": "**X05ZCMB8G0**",
    "name": "XXXXX",
    "comment": "",
    "type": "application/pdf",
    "key": "031cc580-9a75-47b2-98ba-1c1ae89c0609",
    "createdAt": "1530781479272"
  },
  "size": 115255,
  "offset": 115255
}

**Comment by psi-4ward** [comment]
That's correct because if eve can access the json-file, eve has also access to the uploaded binary so storing a the hashed password would not really increase the security.

But anyways, feel free to prepare a PR :)

**Comment by psi-4ward** [comment]
Btw, the password is used to encrypt the files-list on the server so we can not encrypt it.
