### ISSUE TITLE
Resuming download does not work

### ISSUE THREAD

**Issue by lumbric** [psi-4ward/psitransfer#57]
When uploading a huge file the second time (no matter if the first upload was succesful or if tab was closed after 90% progress), it does not resume the first upload. The data folder contains the same file twice with different SID hashes.

Testing using latest docker image.

**Comment by lumbric** [comment]
It seems a bit as if [this was by design](https://github.com/psi-4ward/psitransfer/blob/master/app/src/Upload/store/upload.js#L119):

```javascript
fingerprint: (file) => {
    // include sid to prevent duplicate file detection on different session
    return ["tus", state.sid, file.name, file.type, file.size, file.lastModified].join("-");
},
```
By removing `state.sid` from this list, I was able to make my uploads resume also after I closed and re-opened the browser tab. It still doesn't work via https through my reverse proxy, not sure why, but this shouldn't be a directly related to psitransfer.

I guess not including the sid here could be a security issue. But being able to upload resume the upload even after the tab has been closed sounds like a great feature. I'd preper a pull request, but I am bit lost here how to continue.
@psi-4ward can you give me some more hints why the sid is included?

**Comment by lumbric** [comment]
Hm simply removing the sid from the fingerprint might work (I've successfully tested it), but if I understand the code correctly, it is a bit weird. For a new upload a new sid is generated, but the old one is found via fingerprint and used as endpoint and resume works. I guess it would better not to generate a new sid in this case. Also people uploading different files with same name/size/timestamp might end up in a mixture of files.

See also commit dc52f1456e8097475c (implements the removal of sid).

Slightly off-topic: for the nginx reverse proxy, I had to add the missing lines from the [example config](https://github.com/psi-4ward/psitransfer/blob/master/docs/nginx-ssl-example.conf#L47):

```
              proxy_buffering off;
              proxy_request_buffering off;      # needs nginx version >= 1.7.11
```

**Comment by lumbric** [comment]
Oh, it's not only a small ugliness, pretty much everything is broken when the sid is removed from the fingerprint. After resume one does not get redirected to the correct download page.

**Comment by psi-4ward** [comment]
the sid is used to identify the upload bucket and gets recreated every time you (re)load the upload view.
You can only resume on the same browser tab.

Probably the sid can be encoded in the URI but anyone knowing the sid would be able to add files.

**Comment by lumbric** [comment]
But the sid is already stored in the browser's local storage, so I thought it should be possible to re-use the old sid instead of generating a new one to resume. But I understand now that this would new feature. In the beginning I assumed this should be already supported by tus out of the box.

Btw Resuming without closing the tab (if internet connection is lost) seems to work in Chrome but not in Firefox 63 under Linux. It works when the browser is set to offline, but not if the connection is dropped, I haven't found out why yet. In Firefox it seems to work only by selecting "Work offline". That's why I initially opened this issue, because I thought restarting the upload is the way to resume the upload.
