### ISSUE TITLE
retention issue

### ISSUE THREAD

**Issue by cloudybear** [psi-4ward/psitransfer#6]
Current setup is using the docker container for psitransfer. 

I been testing some transfers and it seems like the retention doesn't seem to be working correctly for me. The only one that works is the one-time download. I've tested the week and few hours retention, but the data and folder is still in the Psi-data directory.

**Comment by psi-4ward** [comment]
Hi, do you use version `1.1.0` ?
If not, please upgrade.

**Comment by cloudybear** [comment]
Thanks, I did the upgrade to 1.1.0, that seems like it's working now.
