### ISSUE TITLE
Docker image "permission denied"

### ISSUE THREAD

**Issue by 0uro** [psi-4ward/psitransfer#60]
Hi, I have a little problem with docker image

docker run -p 0.0.0.0:8080:8080 -e PSITRANSFER_ADMIN_PASS=xxx -v /srv/Public/PSITransfer:/data psitrax/psitransfer
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: permission denied": unknown.
ERRO[0002] error waiting for container: context canceled

I've flattened permissions on target folder, and tried with chown 1000 but nothing works.

What can I do ?

**Comment by psi-4ward** [comment]
So first of all, the default PsiTransfer Port is 3000 so use `-p 0.0.0.0:8080:3000`

But your error seems wired to me. `/app` should be owned by root and only readable by `node` user inside of the container.

You could try to start with `docker run -p 0.0.0.0:8080:3000 -e PSITRANSFER_ADMIN_PASS=xxx -v /srv/Public/PSITransfer:/data -ti psitrax/psitransfer sh` and run `node app.js` from the shell there

**Comment by psi-4ward** [comment]
So looks like you have another problem. If you run the container with `sh` command the app gets not stared. Probably your docker installation is broken
