### ISSUE TITLE
Latest version error

### ISSUE THREAD

**Issue by Onbeskofte** [psi-4ward/psitransfer#66]
Hi,

In the latest update (1.3.0) I see the following error:
psitransfer_1  | TypeError: Cannot read property 'length' of undefined
psitransfer_1  |     at pathtoRegexp (/app/node_modules/path-to-regexp/index.js:63:49)
psitransfer_1  |     at new Layer (/app/node_modules/express/lib/router/layer.js:45:17)
psitransfer_1  |     at Function.route (/app/node_modules/express/lib/router/index.js:494:15)
psitransfer_1  |     at Function.app.(anonymous function) [as get] (/app/node_modules/express/lib/application.js:481:30)
psitransfer_1  |     at Object.<anonymous> (/app/lib/endpoints.js:62:5)
psitransfer_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
psitransfer_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
psitransfer_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
psitransfer_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
psitransfer_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
psitransfer_1  | /app/node_modules/path-to-regexp/index.js:63
psitransfer_1  |   path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))

It seems to be something with the change from node:7-alpine to node:10-alpine.
I've now changed the version back to 1.2.0 and that works fine. 

Could you take a look at that?

**Comment by psi-4ward** [comment]
so you've started the latest docker container?
Pls post the exact start command.

**Comment by Onbeskofte** [comment]
Yes, with docker-compose. So I just use `docker-compose up -d` after that I saw that it kept restarting and spitting out the above error.

**Comment by psi-4ward** [comment]
Pls post the compose file 

Am 17. Dezember 2018 16:53:38 MEZ schrieb Onbeskofte <notifications@github.com>:

**Comment by Onbeskofte** [comment]
psitransfer:
   restart: always
   image: "psitrax/psitransfer:1.2.0"
   ports:
    - 3000:3000/tcp
   volumes:
    - /opt/psitransfer/files:/files:rw
    - /opt/psitransfer/data:/data:rw
    - /opt/psitransfer/data2:/data2:rw
    - /opt/psitransfer/config/config.js:/app/config.js:rw
    - /opt/psitransfer/config/download.html:/app/public/html/download.html:rw
    - /opt/psitransfer/config/upload.html:/app/public/html/upload.html:rw
   environment:
    - PSITRANSFER_UPLOAD_DIR=/data
