### ISSUE TITLE
Question: Upload via Command Line?

### ISSUE THREAD

**Issue by nikhilc89** [psi-4ward/psitransfer#69]
Is it possible to upload files via command-line: curl etc and get back download links rather than use the web browser? 
Trying to automate upload of a bunch of files and this would definitely come in handy.
Cheers.

**Comment by psi-4ward** [comment]
It's not possible because PsiTransfer uses tus.io upload protocol and some randomized bucket IDs.
If you really need this you have to write a (curl/bash/py/what ever) script wich does a POST with the right Upload-Metadata Header and react to the Location response header with a PATCH request.

**Comment by innovarew** [comment]
Shameless plug here. There are TUS protocol clients implementations in Bash. We hacked a quick version that has some experimental support using tusc.sh: https://github.com/innovarew/tusc.sh
