### ISSUE TITLE
How to delete a file?

### ISSUE THREAD

**Issue by RixzZ** [psi-4ward/psitransfer#7]
Hello,

I was testing a few things in psitransfer but I'm having issues with deleting files.

When a user uploads a new file it generates a 12 character string and a folder with that string is created inside the data folder.

I deleted that folder but the link is still valid and there you can see some metadata like the file name, size, etc. The file doesn't exists and can't be previewed or downloaded but the trail is there.

Is there a proper way to delete uploads or am I missing something?

**Comment by psi-4ward** [comment]
You should not delete anything here, PsiTransfer removes the files and folders when the expire time is reached. If you really want to delete things by hand make sure you delete the `xxxx` and `xxxx.json` file and then restart PsiTransfer
