### ISSUE TITLE
Uploading stuck 

### ISSUE THREAD

**Issue by jotiduli** [psi-4ward/psitransfer#70]
Some files are stuck while uploading.
Mainly on 79 and 99%.

**Comment by alapiere** [comment]
Same here .. Retrying again and again. Adding an entry in admin each time.
Really disappointed, cannot push this to users.
nothing in logs apart from access logs

**Comment by psi-4ward** [comment]
Can you check the dev-console of your browser?
Whats your environment?

**Comment by jotiduli** [comment]
@psi-4ward
It is in dev mode.
You can check the live page at: 
https:// share. webin. al

**Comment by draft1** [comment]
Seems still unresolved?

**Comment by psi-4ward** [comment]
See: https://github.com/psi-4ward/psitransfer/issues/96#issuecomment-656111092

Can you validate if chunking solves your problem?
