### ISSUE TITLE
admin pass doesn't work

### ISSUE THREAD

**Issue by wolfy01** [psi-4ward/psitransfer#74]

**Comment by wolfy01** [comment]
I went to /admin, my password was 123 so I could test it, but it says "Access denied!" even when I put the correct password in

**Comment by matthijskooijman** [comment]
I can reproduce this when I set:

    "adminPass": 123,

However, this works:

    "adminPass": "123",

So I presume the password must be a string, making this on one hand a configuration problem, but also a documentation or error reporting problem.

**Comment by wolfy01** [comment]
This is my config.dev.js
```'use strict';

module.exports = {
  "accessLog": 'dev',
  "retentions": {
    "one-time": "one time download",
    "60": "1 Minute",
    "300": "5 Minutes",
    "3600": "1 Hour",
    "21600": "6 Hours",
    "86400": "1 Day",
    "259200": "3 Days",
    "604800": "1 Week",
    "1209600": "2 Weeks"
  },
  "defaultRetention": "3600",
  "adminPass": "hmm"
  // "sslKeyFile": './tmp/cert.key',
  // "sslCertFile": './tmp/cert.pem',
};
```

**Comment by wolfy01** [comment]
I don't anything wrong, however, this still doesn't work

**Comment by greecemunky** [comment]
As you're editing `config.dev.js`, are you setting environment variable `NODE_ENV=dev` ?

Maybe it's not the config file setting that's the issue, but it's potentially not reading the config file you expect.
