### ISSUE TITLE
Only allow upload behind admin page

### ISSUE THREAD

**Issue by rogierlommers** [psi-4ward/psitransfer#83]
I think it would be great to have an option to ONLY allow file uploads behind the /admin interface. I don't want public users to be able to download and my reverse proxy is unable to filter / add basic authentication.

**Comment by Plausible0Bug** [comment]
You may try to block `POST` and `PATCH` request in your reverse proxy.

If your reverse proxy cannot serve as authentication gateway way, you may consider use another layer of protection in the front, proxy the reverse proxy.

**Comment by psi-4ward** [comment]
The upcomming version let's you set a simple password for the upload-app. 

But investigating in auth-rules in your proxy would make more sense cause you can restrict to internal IPs, add basic-auth oder do some more fancy stuff.  With `"uploadAppPath"` config option you can put the upload-app into a defined subdir but also consider to respect POST/PATCH to `/files`
