### ISSUE TITLE
Admin page without password

### ISSUE THREAD

**Issue by senhan07** [psi-4ward/psitransfer#84]
How i can remove password login on admin page?
**Also**
1. can you add a simple big text that shows the SID next to download link Url. ex ACCESS CODE: **CF86**
2. Can you add a input box for the SID / access code with a button on underneath the create optional password input box , so people can access the file by entering the code then it will redirect to the shareUrl

**Comment by psi-4ward** [comment]
I've actually less time (money) to implement further features.

**Comment by Plausible0Bug** [comment]
Strange request, what are the use cases?
For the access code part, do you want a URL shortener instead? Somebody seemed already implemented it and there is an open pull request.
