### ISSUE TITLE
Struggles with the Upload

### ISSUE THREAD

**Issue by fculstudent** [psi-4ward/psitransfer#87]
I tried to run all of the commands specified for npm but my program gets stucked  whenever i press the upload button. It just keeps thinking and doesn't send me any error nor completes the upload.

Already tried to change the ENV variables and every kind of thing that i can remeber. Does anyone have any idea what am i missing?

**Comment by psi-4ward** [comment]
Did you took a look into DevConsole of your browser? (F12)
Did PsiTransfer put anything on the stderr?
