### ISSUE TITLE
PSITRANSFER_DEFAULTRETENTION environment variable not working in Docker

### ISSUE THREAD

**Issue by suckerfish** [psi-4ward/psitransfer#89]
Set PSITRANSFER_DEFAULTRETENTION as an env variable in my docker-compose but the dropdown is blank by default. 

I have also paired this with PSITRANSFER_RETENTIONS variable which is working fine. I have limited it to 'one-time', '1 hour', and '1 day' and those seem fine. 

But if I try to set a default retention it does not listen and the dropdown is blank. 

PSITRANSFER_DEFAULTRETENTION: "3600" 

That's how I have it. I have tried a few derivatives, too. No dice.

**Comment by suckerfish** [comment]
I figured it out. It needed very specific syntax. See below example: 

```
PSITRANSFER_RETENTIONS: '{"86400":"1 Day","259200":"3 Days"}'
      PSITRANSFER_DEFAULT_RETENTION: "86400"
```

**Comment by psi-4ward** [comment]
yes thats right, is the docu unclear for this point? 
https://github.com/psi-4ward/psitransfer/blob/master/docs/configuration.md#environment-variables

if so, feel free to prepare PR for clarification
