### ISSUE TITLE
[Feature Request] Notifications when a file is uploaded and/or downloaded

### ISSUE THREAD

**Issue by suckerfish** [psi-4ward/psitransfer#90]
I am aware the logs may say this, but it would be nice if there was an admin-configurable notification method such as email, pushover, shell script, etc, if a file was either uploaded or downloaded.

Currently I'm using inotifywait for this but it's pretty sloppy.

**Comment by Plausible0Bug** [comment]
You may configure `fileDownloadedWebhook` and `fileUploadedWebhook` and point them to ifttt or any service support webhook.
