### ISSUE TITLE
Upload sometimes get stuck at 100% when connection is unstable

### ISSUE THREAD

**Issue by alaincao** [psi-4ward/psitransfer#96]
Hi,
we had reports from users that sometimes have problem uploading big/huge files. Their upload progress bar being stuck at 100%.
But when I try with bigger files and slower connections than them, all my tests are successfull.
So this is not a maximum file size nor a request timeout problem.
We are using the Docker with a reverse-proxy in between (i.e. 'jwilder/nginx-proxy'). nb: the request buffer is disabled on the proxy.

I am able to reproduce the problem by stopping/restarting the proxy in the middle of an upload, effectively breaking the upload's HTTP connection.
Sometimes, the upload resumes correctly, but not always.
When an upload fails:
- the upload obviously resends the whole file instead of restarting where it was broken because
    a) while the network traffic resumes, the progress bar waits a little while before restarting to increment.
    My guess is that the progress bar resumes its increments after it has resend the X percents already sent
   b) the resulting file in the data/ directory is bigger than the original one
- once 100% progression is reached, the application immediately gets stuck in an infinite loop of empty 'PATCH' http requests (all returning HTTP 204)
e.g.
2020-05-14T17:42:15.391Z POST /files/ 201 1.142 172.19.0.2
2020-05-14T17:42:23.062Z PATCH /files/7f6cd394917c++23d52a20-5fef-416d-aaa9-2552ce1e7411 - - 172.19.0.2
2020-05-14T17:42:56.422Z PATCH /files/7f6cd394917c++23d52a20-5fef-416d-aaa9-2552ce1e7411 204 23811.829 172.19.0.2
2020-05-14T17:42:56.437Z PATCH /files/7f6cd394917c++23d52a20-5fef-416d-aaa9-2552ce1e7411 204 1.169 172.19.0.2
2020-05-14T17:42:56.456Z PATCH /files/7f6cd394917c++23d52a20-5fef-416d-aaa9-2552ce1e7411 204 2.170 172.19.0.2
2020-05-14T17:42:56.474Z PATCH /files/7f6cd394917c++23d52a20-5fef-416d-aaa9-2552ce1e7411 204 1.097 172.19.0.2
[... a lot]

So my guess is that is that when users send big files from their network with unstable firewalls/proxies, they may have problems.
'not sure what I can do to fix/debug the the problem here...

Thanks,

Alain

**Comment by alaincao** [comment]
How does the client knows where to resume its upload? Does it asks the server what was the last byte it received ?
If so, is it possible that, if that request fails, the client beleive it should start at 0?

**Comment by Jayrayme** [comment]
Same Here, only for big files:
behind a reverse proxy, uploads keep reseting to 0%, and the folder is full of 1kb files.
On the local ip it's fine.

**Comment by Haocen** [comment]
This is because the upload request is not properly chunked.
You may try my fix here:
https://github.com/psi-4ward/psitransfer/pull/100

**Comment by psi-4ward** [comment]
Yes I've seens this behave too when some forwarding proxies completely drop the request when the content body reaches a defined size. 

I'll set the upload chunking as suggest by @Haocen to `chunkSize: 5000000,`. Hopefully this solves the problems and we do not need another config option for this.
