### ISSUE TITLE
/app/common.js and /app/upload.js not found

### ISSUE THREAD

**Issue by gilgongo** [psi-4ward/psitransfer#98]
On Ubuntu server 18.04 installed using [systemd instructions](https://github.com/psi-4ward/psitransfer/blob/master/docs/deployment-systemd.md) with Node 14.x using psitransfer [1.3.4](https://github.com/psi-4ward/psitransfer/archive/1.3.4.tar.gz) release. Starting using systemd with [unedited unit file](https://github.com/psi-4ward/psitransfer/blob/master/docs/psitransfer.service).

The web interface shows a blank  page with a logo.

Browser console says `/app/common.js` and `/app/upload.js` not found. I see that this has been reported before (eg #51 and #86 ) but no apparent resolution?

**Comment by psi-4ward** [comment]
Use a (builded) release or build the Frontend-App yourself:

```
cd app
npm install
npm run build
```
