### ISSUE TITLE
Is it possible to make the password field "Required" (and maybe set rules)

### ISSUE THREAD

**Issue by MarshCastle** [psi-4ward/psitransfer#99]
PsiTransfer is brilliant (thank you :D ).

It would be handy for us to be able to force passwords to be set when uploading though (to ensure that all files are "protected").

Is there an easy way to do this with PsiTransfer? If there's an easy way to set password strength, that would be even better!

Thanks in advance for any time spent

**Comment by Plausible0Bug** [comment]
This sounds like a feature request and need some moderate amount of code change.
Author seemed busy.

**Comment by marsh-circle** [comment]
OK - thanks for the info :)

how many hours would you say this would be to implement?

**Comment by Plausible0Bug** [comment]
Forced password:
Server side and frontend change, not big deal, can be controlled by an option in config, 1 human days, need adequate Vue.js and node.js Dev, probably 0.5 human day.

Password strength:
Not sure about this? Do you want a password strength indicator or enforcement? There are probably some Vue.js 3rd party lib can already do this but fine tuning it to match your need can take some time. I would consider this 1 human day.

The total would be around 16 salaried hours for a full stack web developer including code change, doc update, publish new version and prepare docker image, etc.

**Comment by marsh-circle** [comment]
Excellent - thanks for getting back. will pass this over for consideration.

Cheers :)

**Comment by marsh-circle** [comment]
Just for the sake of completeness, the strength would probably be by enforcement, btw - but the first point is more important than the second.
